### ISSUE TITLE
Brightness Fn keys  (F3 F4) non functional

### ISSUE THREAD

**Issue by Viohl** [blmhemu/openaero#4]
I don't understand where the problem is. If you need more information I can provide it.
My guess is that the laptop I have (AERO 15 OLED) isn't necessarily what you are working on, or might behave differently.

Thanks for your work

**Comment by blmhemu** [comment]
Hey ! Are you running Arch Linux ? 
Can you please check whats being given by "xev (or other similar tools)" on pressing Fn + F3 / F4 and also is the VID and PID of the keyboard are same ?

**Comment by blmhemu** [comment]
@Viohl , I think you probably did not install linux-headers. Please run `yay -S linux-headers` and reinstall the package.

**Comment by Viohl** [comment]
Hi, sorry I didn't reply earlier. xev doesn't appear to do anything when FN + F3/F4 is pressed. Linux headers are installed.

**Comment by blmhemu** [comment]
Hey ! Looks like the vid : pid is different. The hid codes being emitted might be different. Can you please check using `hidraw` utility what your keyboard is outputting when media keys are being pressed . If you need more help, let me know.

**Comment by Viohl** [comment]
I run sudo hid-recorder, then I have 4 device options.
/dev/hidraw0
/dev/hidraw1
/dev/hidraw2
/dev/hidraw3

/dev/hidraw2 was the first to give me anything interesting.

FN + F3 outputs;
```
# ReportID: 4 /Array ['00', '00', '7d'] 
E: 000013.480052 4 04 00 00 7d
```
Whereas FN + F4 outputs;
```
# ReportID: 4 /Array ['00', '00', '7e'] 
E: 000068.632844 4 04 00 00 7e
```

Hope this is what you were after. If you need anything else I'll do what I can.

**Comment by blmhemu** [comment]
@Viohl #5 would likely solve your issue.
Please do the following steps and provide feedback :
```
yay -S openaero-driver-dkms-git
```

**Comment by Viohl** [comment]
Superb. It works exactly as expected. Thank you very much!

**Comment by blmhemu** [comment]
I will soon be working on adding support to other media keys also. Thanks for opting in !!!
